version: '3.8'

services:
  app:
    build: .
    container_name: ai-content-pipeline-test # コンテナ名を指定
    ports:
      - "8000:5000"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      SKIP_CONTENT_APIS: ${SKIP_CONTENT_APIS}
      FLASK_APP: "main.py"
    # テスト後に自動的にコンテナを削除したい場合 (開発・テスト環境向け)
    # restart: "no" # これは不要だが、再起動ポリシーの例として
    # 以下の設定はコンテナが終了したときに自動で削除してくれるが、
    # 開発中はコンテナが残っていた方がデバッグしやすい場合もあるので注意
    # volumes:
    #   - .:/app # ホットリロードなどを使いたい場合に有効